### ISSUE TITLE
CI : tee-test (demo-indirect-invocation)  failed

### ISSUE THREAD

**Issue by outofxxx** [litentry/litentry-parachain#1444] opened 2023-03-13 14:35 UTC
### Context

https://github.com/litentry/litentry-parachain/actions/runs/4401532691/jobs/7708733877

When run `second test` on woker2(Using trusted-worker uri wss://integritee-worker-2:2012), which is NOT the primary validateer,
problems occurred.

---

The `error result` of the `second run` is as follows:

* worker1(primary validateer)
1. balance_shield(50503350955afe8a107d6f115dc253eb5d75a3fe37a90b373db26cc12e3c6661, 6000000000000)
`
[2023-03-13T06:28:12Z ERROR integritee_service::ocall_bridge::worker_on_chain_ocall] Could not send extrsinic to node: RpcClient(Extrinsic("extrinsic error code 1002: Verification Error: Runtime error: Execution failed: Execution aborted due to trap: wasm trap: wasm `unreachable` instruction executed\nWASM backtrace:\n\n    0: 0x482cc3 - <unknown>!rust_begin_unwind\n    1: 0x13c24 - <unknown>!core::panicking::panic_fmt::h246cf959bff81f47\n    2: 0x1104d - <unknown>!core::panicking::panic::h178b360d7b370ff2\n    3: 0x409def - <unknown>!<rococo_parachain_runtime::weights::pallet_teerex::WeightInfo<T> as pallet_teerex::weights::WeightInfo>::publish_hash::h9c9b2e8d0e94042b\n    4: 0x3c1d50 - <unknown>!<pallet_teerex::pallet::Call<T> as frame_support::dispatch::GetDispatchInfo>::get_dispatch_info::hfc98a64c5661ac9d\n    5: 0xaf2b7 - <unknown>!<rococo_parachain_runtime::RuntimeCall as frame_support::dispatch::GetDispatchInfo>::get_dispatch_info::h1ff41d74b4f96729\n    6: 0x397ce3 - <unknown>!frame_executive::Executive<System,Block,Context,UnsignedValidator,AllPalletsWithSystem,COnRuntimeUpgrade>::validate_transaction::hd83fb444319d4637\n    7: 0x295c96 - <unknown>!TaggedTransactionQueue_validate_transaction\n: RuntimeApi(\"Execution failed: Execution aborted due to trap: wasm trap: wasm `unreachable` instruction executed\\nWASM backtrace:\\n\\n    0: 0x482cc3 - <unknown>!rust_begin_unwind\\n    1: 0x13c24 - <unknown>!core::panicking::panic_fmt::h246cf959bff81f47\\n    2: 0x1104d - <unknown>!core::panicking::panic::h178b360d7b370ff2\\n    3: 0x409def - <unknown>!<rococo_parachain_runtime::weights::pallet_teerex::WeightInfo<T> as pallet_teerex::weights::WeightInfo>::publish_hash::h9c9b2e8d0e94042b\\n    4: 0x3c1d50 - <unknown>!<pallet_teerex::pallet::Call<T> as frame_support::dispatch::GetDispatchInfo>::get_dispatch_info::hfc98a64c5661ac9d\\n    5: 0xaf2b7 - <unknown>!<rococo_parachain_runtime::RuntimeCall as frame_support::dispatch::GetDispatchInfo>::get_dispatch_info::h1ff41d74b4f96729\\n    6: 0x397ce3 - <unknown>!frame_executive::Executive<System,Block,Context,UnsignedValidator,AllPalletsWithSystem,COnRuntimeUpgrade>::validate_transaction::hd83fb444319d4637\\n    7: 0x295c96 - <unknown>!TaggedTransactionQueue_validate_transaction\\n\")"))
`
2. submitting trusted call to TOP pool: balance_transfer(, , 2000000000000), TOP hash: `0x0b53f69155d55107765da6cbe354a043e14483488df6b40d08d56535f0bee763`

`[2023-03-13T06:34:12Z ERROR integritee_service::ocall_bridge::worker_on_chain_ocall] Could not send extrsinic to node: RpcClient(Extrinsic("Unexpected extrinsic status: Future, stopped watch process prematurely."))
[2023-03-13T06:34:12Z ERROR itp_stf_executor::executor] Stf execute failed: Dispatch("Balance Transfer error: Module(ModuleError { index: 2, error: [2, 0, 0, 0], message: Some(\"InsufficientBalance\") })")`

* worker2
1. Submitting trusted call to TOP pool: balance_shield(, , 6000000000000), TOP hash: `0x14f0be0d6591f20ff3624c5f67b05c5e01a5106bc67b920f5d6b5c2196f1a249`
`
[2023-03-13T06:36:18Z ERROR integritee_service::ocall_bridge::worker_on_chain_ocall] Could not send extrsinic to node: RpcClient(Extrinsic("extrinsic error code 1002: Verification Error: Runtime error: Execution failed: Execution aborted due to trap: wasm trap: wasm `unreachable` instruction executed\nWASM backtrace:\n\n    0: 0x482cc3 - <unknown>!rust_begin_unwind\n    1: 0x13c24 - <unknown>!core::panicking::panic_fmt::h246cf959bff81f47\n    2: 0x1104d - <unknown>!core::panicking::panic::h178b360d7b370ff2\n    3: 0x409def - <unknown>!<rococo_parachain_runtime::weights::pallet_teerex::WeightInfo<T> as pallet_teerex::weights::WeightInfo>::publish_hash::h9c9b2e8d0e94042b\n    4: 0x3c1d50 - <unknown>!<pallet_teerex::pallet::Call<T> as frame_support::dispatch::GetDispatchInfo>::get_dispatch_info::hfc98a64c5661ac9d\n    5: 0xaf2b7 - <unknown>!<rococo_parachain_runtime::RuntimeCall as frame_support::dispatch::GetDispatchInfo>::get_dispatch_info::h1ff41d74b4f96729\n    6: 0x397ce3 - <unknown>!frame_executive::Executive<System,Block,Context,UnsignedValidator,AllPalletsWithSystem,COnRuntimeUpgrade>::validate_transaction::hd83fb444319d4637\n    7: 0x295c96 - <unknown>!TaggedTransactionQueue_validate_transaction\n: RuntimeApi(\"Execution failed: Execution aborted due to trap: wasm trap: wasm `unreachable` instruction executed\\nWASM backtrace:\\n\\n    0: 0x482cc3 - <unknown>!rust_begin_unwind\\n    1: 0x13c24 - <unknown>!core::panicking::panic_fmt::h246cf959bff81f47\\n    2: 0x1104d - <unknown>!core::panicking::panic::h178b360d7b370ff2\\n    3: 0x409def - <unknown>!<rococo_parachain_runtime::weights::pallet_teerex::WeightInfo<T> as pallet_teerex::weights::WeightInfo>::publish_hash::h9c9b2e8d0e94042b\\n    4: 0x3c1d50 - <unknown>!<pallet_teerex::pallet::Call<T> as frame_support::dispatch::GetDispatchInfo>::get_dispatch_info::hfc98a64c5661ac9d\\n    5: 0xaf2b7 - <unknown>!<rococo_parachain_runtime::RuntimeCall as frame_support::dispatch::GetDispatchInfo>::get_dispatch_info::h1ff41d74b4f96729\\n    6: 0x397ce3 - <unknown>!frame_executive::Executive<System,Block,Context,UnsignedValidator,AllPalletsWithSystem,COnRuntimeUpgrade>::validate_transaction::hd83fb444319d4637\\n    7: 0x295c96 - <unknown>!TaggedTransactionQueue_validate_transaction\\n\")"))
`
2. Submitting trusted call to TOP pool: balance_transfer(, , 2000000000000), TOP hash: `0x7e9e795ec935bfebec5f29569f0d4d745f9353c74d265dd821762edc73c5b5d7`
`
[2023-03-13T06:37:06Z ERROR integritee_service::ocall_bridge::worker_on_chain_ocall] Could not send extrsinic to node: RpcClient(Extrinsic("Unexpected extrinsic status: Future, stopped watch process prematurely."))
`

**Comment by Kailai-Wang** [comment] 2023-03-13 14:36
Is it a duplicate of https://github.com/litentry/litentry-parachain/issues/1414 ?

**Comment by BillyWooo** [comment] 2023-03-13 15:20
> Is it a duplicate of #1414 ?

I think so. It looks like this problem will happen when the execution occurs inside the non-primary worker. Need to double check this for reproduce.

**Comment by Kailai-Wang** [comment] 2023-03-13 15:22
I think it has nothing to do with the worker (primary/non-primary), in #1414 I saw the same logs from worker 1 (primary worker).

If this is a duplicate, can we close it and focus on the other?

**Comment by Kailai-Wang** [comment] 2023-03-13 15:22
And who is interested in doing it? :)

**Comment by outofxxx** [comment] 2023-03-13 15:38
This is the error on my pr. I didn't notice that it has been repeated, so this can be closed.

**Closed as completed** 2023-03-13 15:42 UTC
