### ISSUE TITLE
Node setup in Dockerfile is deprecated

### ISSUE THREAD

**Issue by Kailai-Wang** [litentry/litentry-parachain#2150] opened 2023-09-21 10:08 UTC
### Context

The current way of installing node in [build.Dockerfile](https://github.com/litentry/litentry-parachain/blob/1bec274bbc5ccb6d2bfcc2fe546ca0f4713a887d/tee-worker/build.Dockerfile#L103-L106) is deprecated:

<img width="819" alt="image" src="https://github.com/litentry/litentry-parachain/assets/7630809/56346fea-38d7-4a06-b757-a2029ca7b726">

Please replace it with the recommended way

---
:heavy_check_mark: Please set appropriate **labels** and **assignees** if applicable.

**Comment by kziemianek** [comment] 2023-09-21 10:09
@Kailai-Wang it's duplicate of #2148

**Closed as not planned** 2023-09-21 11:06 UTC
Labels: I2-medium, D3-chore
