### ISSUE TITLE
ts-test covers error cases 

### ISSUE THREAD

**Issue by ziming-zung** [litentry/litentry-parachain#1252] opened 2023-02-01 16:18 UTC
### Context
Currently, only normal cases are tested in ts-test, error cases are not tested.  Need to cover as many error cases as possible.

We can leave in the comments below what error case  need to be tested(maybe there are many error cases). e.g. encrypt with error shielding key

**Comment by Kailai-Wang** [comment] 2023-02-01 16:22
can be a follow-up of #1229 - e.g. using a fake TEE shielding key should give you such errors

**Comment by 0xverin** [comment] 2023-02-02 01:30
If use the wrong case to test, will get the wrong event message? (like "someError"). If not, ts-test can't throw an exact error message. @zhizming-zhong

**Comment by ziming-zung** [comment] 2023-02-02 01:45
> If use the wrong case to test, will get the wrong event message? (like "someError"). If not, ts-test can't throw an exact error message. @zhizming-zhong

Yes, ts-test expects to get error messages from the parentchain

**Comment by Kailai-Wang** [comment] 2023-03-06 21:11
Is it a duplicate of https://github.com/litentry/litentry-parachain/issues/1374?

**Comment by jingleizhang** [comment] 2023-03-07 02:35
yes, they are duplicated.

**Comment by jingleizhang** [comment] 2023-03-07 02:36
so close this one.

**Closed as completed by jingleizhang** 2023-03-07 02:36 UTC
Labels: I3-high, D1-feature
