### ISSUE TITLE
ts-tests: retrieve nonce from sidechain

### ISSUE THREAD

**Issue by arieljbirnbaum** [litentry/litentry-parachain#1899] opened 2023-07-17 11:47 UTC
### Context

This comment from @Kailai-Wang in `identity.test.ts`:

> being lazy - the nonce here is hardcoded
> it's better to retrieve the starting nonce from the sidechain and increment
> it for each such request, similar to the construction of substrate tx
> However, beware that we should query the nonce of the enclave-signer-account
> not alice or bob, as it's the indirect calls are signed by the enclave signer

### Task

- [ ] Replace hardcoded nonce with enclave-signer nonce from sidechain

**Comment by Kailai-Wang** [comment] 2023-07-17 14:02
Thanks for having an issue with this 😂 

In DI-sample code there's already something, not necessarily best written though

**Comment by Kailai-Wang** [comment] 2023-07-17 20:43
It's actually a duplicate of https://github.com/litentry/litentry-parachain/issues/1764

So we can work on one and close the other

**Comment by Kailai-Wang** [comment] 2023-07-18 15:25
And please use `author_getNextNonce` to get the nonce - not the public getter

**Comment by arieljbirnbaum** [comment] 2023-07-19 17:44
@Kailai-Wang 

> And please use `author_getNextNonce` to get the nonce - not the public getter

Does this also apply for DI?

**Comment by Kailai-Wang** [comment] 2023-07-22 17:35
> Does this also apply for DI?

Yes - actually only DI is relevant here

**Closed as completed** 2023-08-15 22:27 UTC
Labels: I2-medium, D5-testing
