### ISSUE TITLE
too many requests at the same time to Parachain&TEE

### ISSUE THREAD

**Issue by jingleizhang** [litentry/litentry-parachain#1520] opened 2023-03-24 09:12 UTC

**Comment by jingleizhang** [comment] 2023-04-13 04:22
add @zhouhuitian

**Comment by outofxxx** [comment] 2023-04-14 02:57
@Verin1005 
Is this question a duplicate of this pr https://github.com/litentry/litentry-parachain/pull/1529?

**Comment by outofxxx** [comment] 2023-04-18 07:05
got `verifyIdentityFailed` after a successful IdentityVerified

 set the descriptedLitentry number to 10, then run bulk_identity.test.ts, the issue will appear

discussed in [channel](https://litentry.slack.com/archives/C03KR96989G/p1681747270391789)

**Comment by Kailai-Wang** [comment] 2023-04-20 07:22
What is the context for the issue?

Neither @zhouhuitian nor I have the knowledge - we always need a short summary/background introduction in the issue description.

**Comment by outofxxx** [comment] 2023-04-20 09:39
The purpose of this issue record is to test the request scripts related to multiple accounts in the staging/prod2 environment, mainly the bulk_identity and bulk_vc scripts in ts-test.
The issues currently found are the same as those discussed in the channel above, where after verifyIdentity succeeded, a failed event appeared again.

**Comment by 0xverin** [comment] 2023-07-10 06:44
Since the `utility` and `bulk` tests are already covered in ts-tests, [this issue](https://github.com/litentry/litentry-parachain/issues/1562)(encountered during stress testing) needs further investigation. For now, let's lower the priority to low. If there is a need for stress testing in the future, we can raise the priority back to high. cc @zhouhuitian

**Comment by outofxxx** [comment] 2023-09-19 06:56
The stress testing covered this case already, so let's close it.

**Closed as completed by outofxxx** 2023-09-19 06:56 UTC
Labels: I1-low, D1-feature
